### ISSUE TITLE
json decode fails when receiving multiple http headers

### ISSUE THREAD

**Issue by elmarbransch** [pxlrbt/wordpress-cf7-weclapp-integration#1]
Hi Dennis,

I used your client to do some weclapp automation ;-)

I experienced - at least in my scenario - that weclapp returns multiple http headers and simply exploding the request result into header and body does not work.

https://github.com/pxlrbt/wordpress-contact-form-7-weclapp/blob/ab4d76608de7e8ff2b9b3fb0524e29b8379d926b/lib/Http/JsonClient.php#L45

I fixed in on my end to explode it the same way and use only the last part as the body.

Best
-Elmar

**Comment by pxlrbt** [comment]
Hey Elmar,

sorry for the delay. I didn't watch my own repo and wasn't notified.

> simply exploding the request result into header and body does not work.

Hm, actually multiple headers should not be an issue if the format is correct. I did not have any issues so far.

But I probably will be swapping my own implementation with guzzle at some time anyway.

Regards
Dennis

**Comment by elmarbransch** [comment]
Hi Dennis, thanks for the response.

It's good to rely on standard libs - like guzzle. But on the other hand I do really like simple one-file-libraries, where you can oversee all the details :-)
I see you already pushed a new version.

All the best
-Elmar
